/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskTopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        data = new javax.swing.JMenu();
        newStaff = new javax.swing.JMenuItem();
        modifyStaff = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenuItem();
        showAllStaff = new javax.swing.JMenuItem();
        showAllUsers = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        ph = new javax.swing.JMenu();
        stock = new javax.swing.JMenuItem();
        phReports = new javax.swing.JMenuItem();
        emails = new javax.swing.JMenu();
        send = new javax.swing.JMenuItem();
        showAllEmails = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        reportIssue = new javax.swing.JMenuItem();
        updates = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setPreferredSize(new java.awt.Dimension(900, 700));

        DeskTopPane.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout DeskTopPaneLayout = new javax.swing.GroupLayout(DeskTopPane);
        DeskTopPane.setLayout(DeskTopPaneLayout);
        DeskTopPaneLayout.setHorizontalGroup(
            DeskTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        DeskTopPaneLayout.setVerticalGroup(
            DeskTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        data.setText("Data");
        data.setPreferredSize(new java.awt.Dimension(39, 20));

        newStaff.setText("Add new ");
        newStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStaffActionPerformed(evt);
            }
        });
        data.add(newStaff);

        modifyStaff.setText("Modify info");
        modifyStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyStaffActionPerformed(evt);
            }
        });
        data.add(modifyStaff);

        Search.setText("Search by ID");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        data.add(Search);

        showAllStaff.setText("Show all staff");
        showAllStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllStaffActionPerformed(evt);
            }
        });
        data.add(showAllStaff);

        showAllUsers.setText("Show all users");
        showAllUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllUsersActionPerformed(evt);
            }
        });
        data.add(showAllUsers);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        data.add(exit);

        jMenuBar1.add(data);

        ph.setText("Pharmacy");
        ph.setPreferredSize(new java.awt.Dimension(68, 20));

        stock.setText("Current Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        ph.add(stock);

        phReports.setText("Reports");
        ph.add(phReports);

        jMenuBar1.add(ph);

        emails.setText("Emails");
        emails.setPreferredSize(new java.awt.Dimension(50, 20));

        send.setText("Send E-mail");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        emails.add(send);

        showAllEmails.setText("Show E-mails");
        emails.add(showAllEmails);

        jMenuBar1.add(emails);

        help.setText("Help");

        reportIssue.setText("Report Issue");
        reportIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIssueActionPerformed(evt);
            }
        });
        help.add(reportIssue);

        updates.setText("Check For Updates");
        help.add(updates);

        about.setText("About");
        help.add(about);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskTopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskTopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        Medicines m = new Medicines();
        DeskTopPane.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_stockActionPerformed

    private void reportIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIssueActionPerformed
        Issue is = new Issue();
        DeskTopPane.add(is);
        is.setSize(500, 500);
        is.setVisible(true);
    }//GEN-LAST:event_reportIssueActionPerformed

    private void newStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStaffActionPerformed
        NewStaff staff = new NewStaff();
        DeskTopPane.add(staff);
        staff.setVisible(true);
        
    }//GEN-LAST:event_newStaffActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        SearchByID search = new SearchByID();
        DeskTopPane.add(search);
        search.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        SendE em = new SendE();
        DeskTopPane.add(em);
        em.setVisible(true);
    }//GEN-LAST:event_sendActionPerformed

    private void showAllStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllStaffActionPerformed
        ShowStaff sas = new ShowStaff();
        DeskTopPane.add(sas);
        sas.setVisible(true);
    }//GEN-LAST:event_showAllStaffActionPerformed

    private void modifyStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyStaffActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void showAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllUsersActionPerformed
        ShowUsers su = new ShowUsers();
        DeskTopPane.add(su);
        su.setVisible(true);
    }//GEN-LAST:event_showAllUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskTopPane;
    private javax.swing.JMenuItem Search;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu data;
    private javax.swing.JMenu emails;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem modifyStaff;
    private javax.swing.JMenuItem newStaff;
    private javax.swing.JMenu ph;
    private javax.swing.JMenuItem phReports;
    private javax.swing.JMenuItem reportIssue;
    private javax.swing.JMenuItem send;
    private javax.swing.JMenuItem showAllEmails;
    private javax.swing.JMenuItem showAllStaff;
    private javax.swing.JMenuItem showAllUsers;
    private javax.swing.JMenuItem stock;
    private javax.swing.JMenuItem updates;
    // End of variables declaration//GEN-END:variables
}
